bei2-master/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'ratings/index'

  get 'ratings/show'

  get 'ratings/new'
  resources :ingredients
  root "ingredients#index"

  get 'ratings_controller/index'

  get 'ratings_controller/show'

  get 'ratings_controller/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'recipes/list'
  get 'recipes/search'

  get 'recipes/foods'
  get 'recipes/findrecipes'
  get 'recipes/recipeinfo'
  get 'recipes/steps'
  get 'recipes/getsteps'
  resources :recipes
  resources :ratings
end

bei2-master/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :user
end

bei2-master/app/models/rating.rb
class Rating < ActiveRecord::Base
end

bei2-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ingredients
end

bei2-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bei2-master/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    before_action :find_ingredient, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index]
    #this code displayes the ingredients and their quantities
    def index
        @ingredient= Ingredient.all.order("created_at DESC")
    end
    #this code shows the ingredient and quantity
    def show
    end
    #this code creates a new ingredient
    def new
        # @ingredient = Ingredient.new
        @ingredient = current_user.ingredients.build
    end
    #this code creates a new ingredient with proper quantity
    def create
        # @ingredient= Ingredient.new(ingredient_params)
        @ingredient = current_user.ingredients.build(ingredient_params)
        if @ingredient.save
            redirect_to @ingredient, notice: "Successfully added new ingredient"
        else
            render 'new'
        end
    end
    #this code edits the ingredient name
    def edit
    end
    #this code updates the ingredient quantity
    def update
        if @ingredient.update(ingredient_params)
            redirect_to @ingredient
        else
            render 'edit'
        end
    end
    #this code deletes the ingredient
    def destroy
        @ingredient.destroy
        redirect_to root_path, notice: "Successfully deleted ingredient"
    end

    private
    #this code ensures the correct data is typed into the parameters
    def ingredient_params
        params.require(:ingredient).permit(:name, :quantity)
    end
    #this code finds the ingredient IDs
    def find_ingredient
        @ingredient = Ingredient.find(params[:id])
    end

end

bei2-master/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
  end

  def show
  end
  #this code creates a new rating
  def new
    @rating = Rating.new
  end
  #this code allows a user to add the proper data to the recipe
  def create
    rating = Rating.new(rating_params)
    rating.save!
    redirect_to action: 'index'
  end
  #this code required the proper rating information
  def rating_params 
    params.require(:rating).permit(:recipe_id, :rating)
  end
end

bei2-master/app/controllers/recipes_controller.rb
require 'unirest'

class RecipesController < ApplicationController
  def list
  end

  def search
  render plain: "bazinga " + params['query'].inspect
  end

  def foods
  end

	def steps
	end
	#this function displays the proper steps for the recipe
  def getsteps
		@hide_menu = true

    puts "In Steps"
    recId = params['query'].inspect
    #this is the link to the API
    url = "https://spoonacular-recipe-food-nutrition-v1.p.mashape.com/recipes/" + recId[1..-2] + "/analyzedInstructions?stepBreakdown=true"
    stepss = Unirest.get url,
      headers:{
        "X-Mashape-Key" => "UpZLcnOR83mshtXvuIOPFXBkfhn5p1UWi1ejsnsTLWoVXrOppm",
        "Accept" => "application/json"
      }
    allSteps = stepss.body

    recSteps = Hash.new

    counter = 1
    #this is how the recipe information is formatted
    allSteps.each do |key|
      key.each do |key2,steps|
        if(key2.eql? "steps")
          steps.each do |step|
            step.each do |key3, lastStep|
              if(key3.eql? "step")
                recSteps[counter] = lastStep
                counter += 1
                #this gives each step a number, for ease of use
              end
            end
          end
        end
      end
    end
    puts recSteps

    @recipeData = recSteps
    render template: "recipes/data3"
  end
  #this function displays the recipes on the recipe search page
  def findrecipes
		@hide_menu = true
    puts "In Find Recipes"
    #this is where the data for the searching of recipes gets routed into
    input = params['query'].inspect

    ingreds = input.split(',')

    input = ingreds.join("%2C")
    #this is the api 
    url = "https://spoonacular-recipe-food-nutrition-v1.p.mashape.com/recipes/findByIngredients?fillIngredients=false&ingredients=" +  input + "&limitLicense=false&number=5&ranking=1"

    res = Unirest.get url,
      headers:{
        "X-Mashape-Key" => "UpZLcnOR83mshtXvuIOPFXBkfhn5p1UWi1ejsnsTLWoVXrOppm",
        "Accept" => "application/json"
      }

    recipes = res.body
    #for each recipe that gets returned, the following information is routed into the recipe results page
    recipes.each do |recipe|
      url2 = url2 = "https://spoonacular-recipe-food-nutrition-v1.p.mashape.com/recipes/" + recipe['id'].to_s + "/information?includeNutrition=false"

      res2 = Unirest.get url2,
      headers:{
        "X-Mashape-Key" => "UpZLcnOR83mshtXvuIOPFXBkfhn5p1UWi1ejsnsTLWoVXrOppm",
        "Accept" => "application/json"
      }

      price = ("$" + (0.01 * res2.body['pricePerServing']).to_s)[0..5]

      recipe['price'] = price
      #this is the price of a recipe per serving

    end

    @recipeData = recipes
    render template: "recipes/data"
  end
end

bei2-master/app/helpers/application_helper.rb
module ApplicationHelper
end

bei2-master/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

bei2-master/app/helpers/ratings_helper.rb
module RatingsHelper
end

bei2-master/app/helpers/recipes_helper.rb
module RecipesHelper
end

bei2-master/app/views/ingredients/_form.html.haml
= simple_form_for @ingredient, html: { multipart: true } do |f|
    - if @ingredient.errors.any?
        /this section of code is error message handling in the event the ingredient is not saved
        #errors
            %p
                = @ingredient.errors.count
                Prevented this ingredient from saving
        
            %ul
                - @ingredient.errors.full_messages.each do |msg|
                    %li= msg
        /this section of code submits the form
    .row
        .panel-body.col-lg-3
            =f.input :name, input_html: { class: 'form-control' }
            =f.input :quantity, input_html: { class: 'form-control' }
    .row
        .col-lg-5
            = f.button :submit, class: "btn btn-primary"

bei2-master/app/views/ingredients/edit.html.haml
/this code is the header for the edit recipe page
%h1 Edit Recipe

= render 'form'

bei2-master/app/views/ingredients/index.html.haml
/this logic is to determine what to display if a user is signed in or not.
-if user_signed_in?
  %h1 Your Pantry
  - @ingredient.each do |ingredient|
    %h2= link_to ingredient.name, ingredient
-else
  %h1 Welcome! Sign in to see your pantry

bei2-master/app/views/ingredients/new.html.haml
/this page displays the header information on the page that displays a new ingredient that the user is adding to their pantry
%h1 New Ingredient

= render 'form'

%br/

=link_to "Back", root_path, class: "btn btn-default"

bei2-master/app/views/ingredients/show.html.haml
/this page determines what to display on the pantry page if a user is signed in
-if user_signed_in?
    %h1= @ingredient.name
    %p= @ingredient.quantity

    = link_to "Back", root_path, class: "btn btn-default"
    = link_to "Edit", edit_ingredient_path, class: "btn btn-default"
    = link_to "Delete", ingredient_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"

bei2-master/app/views/layouts/application.html.haml
!!! 5
%html
/this is the main page
%head
  %title
  / this information is for displaying the proper formatting using the css and javascript files
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  - unless @hide_menu
    %nav.navbar.navbar-default
      .container
        .navbar-brand= link_to "Mom", root_path
        /this information is displayed if a user is signed in
        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Search", recipes_foods_path
            %li=link_to "Ingredient", new_ingredient_path
            %li=link_to "Sign Out", destroy_user_session_path, method: :delete
            /otherwise this information is displayed
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Search", recipes_foods_path
            %li=link_to "Sign Up", new_user_registration_path
            %li=link_to "Sign In", new_user_session_path
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert"
    = yield

bei2-master/app/views/ratings/add_rating.html.erb
<%#-this page is the header for the adding ratings page -%>
<h1>Ratings#add_rating</h1>
<p>Find me in app/views/ratings/add_rating.html.erb</p>

bei2-master/app/views/ratings/index.html.erb
<h1>Rating submitted successfully!</h1>
<%#-this page is the sucess pop up for the adding ratings page -%>

bei2-master/app/views/ratings/new.html.erb
<body>
<h1>Rate a Recipe</h1>
<%#-this page is the adding ratings page -%>

<%= form_for(@rating) do |f| %>
<div class="row">
<div class="col-xs-3">
  <%#-this section is where the recipe ID goes -%>
  <%= f.label :recipe_id, :class => "input-xlarge" %>
  <%#-this is the submit button to find the recipe-%>
  <%= f.text_field :recipe_id, :class => "form-control" %>
</div>
</div>
<div class="row">
<div class="col-xs-3">
  <%#-these are the 5 buttons for chosing a rating -%>
  <div class="radio-inline">
    <label><%= f.radio_button :rating, 5, checked: true %> 5</label>
  </div>
  <div class="radio-inline">
    <label><%= f.radio_button :rating, 4 %> 4</label>
  </div>
  <div class="radio-inline">
    <label><%= f.radio_button :rating, 3 %> 3</label>
  </div>
  <div class="radio-inline">
    <label><%= f.radio_button :rating, 2 %> 2</label>
  </div>
  <div class="radio-inline">
    <label><%= f.radio_button :rating, 1 %> 1</label>
  </div>
  <%#-this is the submit rating button -%>
  <div class="form-actions"><%= f.submit :class => "btn btn-primary" %></div>
<% end %>
</div>
</div>
</div>
</body>

bei2-master/app/views/ratings/show.html.erb
<%#-this page displays the ratings -%>
<h1>Ratings#show</h1>
<p>Find me in app/views/ratings/show.html.erb</p>

bei2-master/app/views/recipes/data.html.erb
<%#-this page is the ratings results page -%>
<body>
	<div>
		<%#-the return table is striped for easy viewing and pre assign the width to ensure it fills the space without an excess of line wraparounds-%>
 		<table class="table table-striped" width="1000">
			<thead>
				<tr><%#-for each item in the recipe database, we display the keys as the table header -%>
					<% @recipeData[0].keys.each do |recipeElement| %>
						<th>
							<% if !(['imageType'].include?(recipeElement))%>
								<%= recipeElement.capitalize  %>
								<%#-the elements are capitalized -%>
							<% end %>
						</th>
					<% end %>
					<th>Rating</th>
					<%#- we add the rating in the header because it is not gathered from the api -%>
				</tr>
			</thead>
			<tbody>
				<%#-for each returnable recipe, we sort by whether is is an image or not, and whether or not the item is linkable to a seperate page -%>
				<% @recipeData.each do |recipe| %>
					<tr>
						<% recipe.keys.each do |recipeElement| %>
							<td>
								<% if (['f2f_url','source_url','publisher_url'].include?(recipeElement)) %>
									<a href="<%= recipe[recipeElement] %>">
										<%= recipe[recipeElement] %>
						 			</a>
								<% else %>
									<% if (['image_url','image'].include?(recipeElement))%>
										<img src="<%= recipe[recipeElement] %>" height="100" width="100">
										<%#-this displays an image of the recipe -%>
									<% else %>
										<% if !(['imageType'].include?(recipeElement))%>
											<%= recipe[recipeElement] %>
											<% if (['title'].include?(recipeElement))%>
													<%= link_to "(See Steps)", recipes_steps_path %>
													<%#-this links the page to the specific recipe -%>
											<% end %>
										<% end %>
									<% end %>
							<% end %>
							</td>
						<% end %>
						<td>
							<!-- Print out ratings -->
							<% @recipe_rating = Rating.find_by(recipe_id: recipe['id'].to_i) %>
								<% if @recipe_rating %>
									<b><%= @recipe_rating.rating%></b>
								<% else %>
								<%#-this links to the rating page -%>
								<%=link_to "Rate", new_rating_path %>
							<%end %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</body>

bei2-master/app/views/recipes/data3.html.erb
<%#-this page is the recipe instruction page -%>
<body>
	<div>
		<%#-auto size the table -%>
<table class="table" width="1000">
	<thead>
	<tr><%#-only two columns needed -%>
			<th>Step #</th>
			<th>Instruction</th>
	</tr>
</thead>
<tbody>
	<%#-this displays the proper steps taken from the api for the recipe -%>
	<% @recipeData.each do |num, step| %>
		<tr>
				<td>
							<%= num  %>
				</td>
				<td>
							<%= step  %>
				</td>
		</tr>
	<% end %>
	</tbody>
</table>
</div>
</body>

bei2-master/app/views/recipes/foods.html.erb
<h1>Find Recipes</h1>

<%#-this page is the ratings results page -%>
<div class="row">
    <div class="col-sm-4 form-group">
        <%#-this is the form to describe what your are searching for -%>
        <textarea class="form-control" id="searchRecipesId"></textarea>
    </div>
    <div class="col-sm-4">
        <%#-this button generates recipes from the form text -%>
        <button type="button" class="btn btn-default" id="allRecipesButt">Generate Recipes!</button>
    </div>
	<div class="col-lg-12" id="resultsRecipesId"></div>
</div>

bei2-master/app/views/recipes/steps.html.erb
<h1>Find Steps</h1>
<%#-this is the recipe steps page-%>
<div class="row">
    <div class="col-sm-4 form-group">
        <%#-the recipe Id needs to be pasted in here to get the recipe -%>
        <textarea class="form-control" id="getStepsId"></textarea>
    </div>
    <div class="col-sm-4">
        <%#-this button leads to the steps of the selected recipe -%>
        <button type="button" class="btn btn-default" id="getStepsButt">Find Recipe Steps!</button>
    </div>
	<div class="col-lg-12" id="resultsStepsId"></div>
</div>